# Generated by Django 4.2.2 on 2023-06-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_name',
            field=models.CharField(default='', max_length=221),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
