# Generated by Django 4.2.2 on 2023-06-23 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_client_name_booking_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
